CREATE TABLE IF NOT EXISTS price_change (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    advert_id BIGINT NOT NULL REFERENCES advert(id),
    price BIGINT NOT NULL DEFAULT 0,
    date_creation TIMESTAMP NOT NULL DEFAULT NOW(),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);