CREATE TABLE IF NOT EXISTS price_change (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    advert_id BIGINT NOT NULL REFERENCES advert(id),
    price NUMERIC(10, 0) NOT NULL DEFAULT 0,
    creation_date TIMESTAMP NOT NULL DEFAULT NOW(),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);