CREATE TABLE IF NOT EXISTS street (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    town_id BIGINT NOT NULL REFERENCES town(id),
    name TEXT CONSTRAINT name_length CHECK ( char_length(name) <= 120) NOT NULL
);