version: "3.9"

services:
  db:
    container_name: postgres
    restart: always
    build:
      context: .
      dockerfile: ./build/postgres.Dockerfile
    volumes:
      - type: volume
        source: postgresdb-data
        target: /var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - ${DB_PORT}:5432
    networks:
      - tean-network

  main:
    depends_on:
      - db
    container_name: mainService
    build:
      context: .
      dockerfile: ./build/main.Dockerfile
    ports:
      - '8080:8080'
    env_file:
      - ./.env
    volumes:
      - "${BASE_DIR}:/docker-cian/images"
    networks:
      - tean-network

  tean-auth:
    env_file:
      - ./.env
    container_name: ${GRPC_AUTH_CONTAINER_IP}
    restart: always
    expose:
      - "${GRPC_AUTH_PORT}"
    depends_on:
      - db
    networks:
      - tean-network

  tean-user:
    env_file:
      - ./.env
    container_name: ${GRPC_USER_CONTAINER_IP}
    restart: always
    expose:
      - "${GRPC_USER_PORT}"
    depends_on:
      - db
    networks:
      - tean-network

  tean-advert:
    env_file:
       - ./.env
    container_name: ${GRPC_ADVERT_CONTAINER_IP}
    restart: always
    expose:
      - "${GRPC_ADVERT_PORT}"
    depends_on:
      - db
    networks:
      - tean-network


volumes:
  postgresdb-data:
    driver: local
