// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonB2fb3a99Decode20241TeaStealersInternalModels(in *jlexer.Lexer, out *FlatSquareProperties) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "floor":
			out.Floor = int(in.Int())
		case "floorGeneral":
			out.FloorGeneral = int(in.Int())
		case "roomCount":
			out.RoomCount = int(in.Int())
		case "squareGeneral":
			out.SquareGeneral = float64(in.Float64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB2fb3a99Encode20241TeaStealersInternalModels(out *jwriter.Writer, in FlatSquareProperties) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"floor\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Floor))
	}
	{
		const prefix string = ",\"floorGeneral\":"
		out.RawString(prefix)
		out.Int(int(in.FloorGeneral))
	}
	{
		const prefix string = ",\"roomCount\":"
		out.RawString(prefix)
		out.Int(int(in.RoomCount))
	}
	{
		const prefix string = ",\"squareGeneral\":"
		out.RawString(prefix)
		out.Float64(float64(in.SquareGeneral))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FlatSquareProperties) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB2fb3a99Encode20241TeaStealersInternalModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FlatSquareProperties) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB2fb3a99Encode20241TeaStealersInternalModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FlatSquareProperties) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB2fb3a99Decode20241TeaStealersInternalModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FlatSquareProperties) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB2fb3a99Decode20241TeaStealersInternalModels(l, v)
}
func easyjsonB2fb3a99Decode20241TeaStealersInternalModels1(in *jlexer.Lexer, out *FlatRectangleProperties) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "floor":
			out.Floor = int(in.Int())
		case "floorGeneral":
			out.FloorGeneral = int(in.Int())
		case "roomCount":
			out.RoomCount = int(in.Int())
		case "squareGeneral":
			out.SquareGeneral = float64(in.Float64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB2fb3a99Encode20241TeaStealersInternalModels1(out *jwriter.Writer, in FlatRectangleProperties) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"floor\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Floor))
	}
	{
		const prefix string = ",\"floorGeneral\":"
		out.RawString(prefix)
		out.Int(int(in.FloorGeneral))
	}
	{
		const prefix string = ",\"roomCount\":"
		out.RawString(prefix)
		out.Int(int(in.RoomCount))
	}
	{
		const prefix string = ",\"squareGeneral\":"
		out.RawString(prefix)
		out.Float64(float64(in.SquareGeneral))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FlatRectangleProperties) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB2fb3a99Encode20241TeaStealersInternalModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FlatRectangleProperties) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB2fb3a99Encode20241TeaStealersInternalModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FlatRectangleProperties) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB2fb3a99Decode20241TeaStealersInternalModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FlatRectangleProperties) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB2fb3a99Decode20241TeaStealersInternalModels1(l, v)
}
func easyjsonB2fb3a99Decode20241TeaStealersInternalModels2(in *jlexer.Lexer, out *FlatProperties) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "floor":
			out.Floor = int(in.Int())
		case "floorGeneral":
			out.FloorGeneral = int(in.Int())
		case "ceilingHeight":
			out.CeilingHeight = float64(in.Float64())
		case "roomCount":
			out.RoomCount = int(in.Int())
		case "squareGeneral":
			out.SquareGeneral = float64(in.Float64())
		case "squareResidential":
			out.SquareResidential = float64(in.Float64())
		case "apartment":
			out.Apartment = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB2fb3a99Encode20241TeaStealersInternalModels2(out *jwriter.Writer, in FlatProperties) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"floor\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Floor))
	}
	{
		const prefix string = ",\"floorGeneral\":"
		out.RawString(prefix)
		out.Int(int(in.FloorGeneral))
	}
	{
		const prefix string = ",\"ceilingHeight\":"
		out.RawString(prefix)
		out.Float64(float64(in.CeilingHeight))
	}
	{
		const prefix string = ",\"roomCount\":"
		out.RawString(prefix)
		out.Int(int(in.RoomCount))
	}
	{
		const prefix string = ",\"squareGeneral\":"
		out.RawString(prefix)
		out.Float64(float64(in.SquareGeneral))
	}
	{
		const prefix string = ",\"squareResidential\":"
		out.RawString(prefix)
		out.Float64(float64(in.SquareResidential))
	}
	{
		const prefix string = ",\"apartment\":"
		out.RawString(prefix)
		out.Bool(bool(in.Apartment))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FlatProperties) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB2fb3a99Encode20241TeaStealersInternalModels2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FlatProperties) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB2fb3a99Encode20241TeaStealersInternalModels2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FlatProperties) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB2fb3a99Decode20241TeaStealersInternalModels2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FlatProperties) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB2fb3a99Decode20241TeaStealersInternalModels2(l, v)
}
func easyjsonB2fb3a99Decode20241TeaStealersInternalModels3(in *jlexer.Lexer, out *Flat) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int64(in.Int64())
		case "buildingId":
			out.BuildingID = int64(in.Int64())
		case "floor":
			out.Floor = int(in.Int())
		case "ceilingHeight":
			out.CeilingHeight = float64(in.Float64())
		case "roomCount":
			out.RoomCount = int(in.Int())
		case "squareGeneral":
			out.SquareGeneral = float64(in.Float64())
		case "squareResidential":
			out.SquareResidential = float64(in.Float64())
		case "apartment":
			out.Apartment = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB2fb3a99Encode20241TeaStealersInternalModels3(out *jwriter.Writer, in Flat) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"buildingId\":"
		out.RawString(prefix)
		out.Int64(int64(in.BuildingID))
	}
	{
		const prefix string = ",\"floor\":"
		out.RawString(prefix)
		out.Int(int(in.Floor))
	}
	{
		const prefix string = ",\"ceilingHeight\":"
		out.RawString(prefix)
		out.Float64(float64(in.CeilingHeight))
	}
	{
		const prefix string = ",\"roomCount\":"
		out.RawString(prefix)
		out.Int(int(in.RoomCount))
	}
	{
		const prefix string = ",\"squareGeneral\":"
		out.RawString(prefix)
		out.Float64(float64(in.SquareGeneral))
	}
	{
		const prefix string = ",\"squareResidential\":"
		out.RawString(prefix)
		out.Float64(float64(in.SquareResidential))
	}
	{
		const prefix string = ",\"apartment\":"
		out.RawString(prefix)
		out.Bool(bool(in.Apartment))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Flat) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB2fb3a99Encode20241TeaStealersInternalModels3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Flat) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB2fb3a99Encode20241TeaStealersInternalModels3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Flat) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB2fb3a99Decode20241TeaStealersInternalModels3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Flat) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB2fb3a99Decode20241TeaStealersInternalModels3(l, v)
}
