CREATE TABLE IF NOT EXISTS priceChanges (
    id UUID NOT NULL PRIMARY KEY,
    advertId UUID NOT NULL REFERENCES adverts(id) ON DELETE CASCADE,
    price NUMERIC(10, 0),
    dateCreation TIMESTAMP NOT NULL DEFAULT NOW(),
    isDeleted BOOLEAN NOT NULL DEFAULT FALSE
);