// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package utils

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson79a3de99Decode20241TeaStealersInternalPkgUtils(in *jlexer.Lexer, out *respSuccess) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "statusCode":
			out.StatusCode = int(in.Int())
		case "message":
			out.Message = string(in.String())
		case "payload":
			if m, ok := out.Payload.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.Payload.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.Payload = in.Interface()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson79a3de99Encode20241TeaStealersInternalPkgUtils(out *jwriter.Writer, in respSuccess) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"statusCode\":"
		out.RawString(prefix[1:])
		out.Int(int(in.StatusCode))
	}
	if in.Message != "" {
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	{
		const prefix string = ",\"payload\":"
		out.RawString(prefix)
		if m, ok := in.Payload.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.Payload.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.Payload))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v respSuccess) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson79a3de99Encode20241TeaStealersInternalPkgUtils(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v respSuccess) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson79a3de99Encode20241TeaStealersInternalPkgUtils(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *respSuccess) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson79a3de99Decode20241TeaStealersInternalPkgUtils(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *respSuccess) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson79a3de99Decode20241TeaStealersInternalPkgUtils(l, v)
}
func easyjson79a3de99Decode20241TeaStealersInternalPkgUtils1(in *jlexer.Lexer, out *respError) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "message":
			out.Message = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson79a3de99Encode20241TeaStealersInternalPkgUtils1(out *jwriter.Writer, in respError) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix[1:])
		out.String(string(in.Message))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v respError) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson79a3de99Encode20241TeaStealersInternalPkgUtils1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v respError) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson79a3de99Encode20241TeaStealersInternalPkgUtils1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *respError) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson79a3de99Decode20241TeaStealersInternalPkgUtils1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *respError) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson79a3de99Decode20241TeaStealersInternalPkgUtils1(l, v)
}
